# desafioDio

Desafio da Dio sobre contador no qual o usuário irá colocar dois números que serão pedidos pelo terminal e já estão configurados no sistema:
![image](https://github.com/user-attachments/assets/b0b43f2a-6120-4c5f-a454-8350db567a70)

E quando o primeiro número digitado é maior do que o segundo dá um erro no qual utilizei a exceção try catch, mas também criei uma classe nova com a mensagem e para fechar utilizei o finally:
![image](https://github.com/user-attachments/assets/093899b8-5a55-49ad-853c-22b1d89c1c93)

